### ISSUE TITLE
Maybe mention issues with radian

### ISSUE THREAD

**Issue by sebffischer** [pfistfl/yahpo_gym#35]
WhenI was using yahpo gym with radian (https://github.com/randy3k/radian) the instructions in the README did not work (radian is written in python therefore it already initializes a python version that then conflicts with the python version used by the yahpo_gym environment) 

Maybe this can be mentioned in the README to avoid problem for others

**Comment by pfistfl** [comment]
fixed

**Comment by pfistfl** [comment]
mentioned in readme
